### ISSUE TITLE
.dev version 1.8.3 not showing safari, mail, and camera

### ISSUE THREAD

**Issue by ghost** [colbyfayock/minimal.iOS.8#10]
![image](https://cloud.githubusercontent.com/assets/11992896/7469965/988f8fe6-f34b-11e4-9ec8-58b5bddbb87d.jpg)

Here's the image in 1.8.1:
![image](https://cloud.githubusercontent.com/assets/11992896/7469937/677d7d6e-f34b-11e4-89f2-d433f4a1d65e.jpg)

**Comment by ghost** [comment]
sorry, include photos too

EDIT: if you look closely, the other icons are changed subtly too..

**Comment by colbyfayock** [comment]
I'll try and get these fixes on the next dev release. I did a refresh of the color scheme to make it more consistent theme-wide. As long as it's themed, it's as intended (unless it's blurry or something).

**Comment by ghost** [comment]
Well, I bought your theme for the pastel colors, but its okay. :D

**Comment by colbyfayock** [comment]
my theme is free :+1:

**Comment by ghost** [comment]
Oh yeah.. got*

**Comment by colbyfayock** [comment]
@nellthan22 they're all fixed? :D

**Comment by ghost** [comment]
sorry, closed wrong issue

**Comment by colbyfayock** [comment]
@nellthan22 are any of these still an issue?

**Comment by colbyfayock** [comment]
others noted this is still an issue. keeping in as ticket, will try to get in next bug fix

**Comment by colbyfayock** [comment]
@nellthan22 dev release 2.0.3 should fix all of these properly. let me know if they dont on yours
