### ISSUE TITLE
Add Smartplayer, Camera Roll Bug iPad

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/minimal.iOS.8#11]
I am requesting that the app Smartplayer (bundle ID com.shaddeen.SmartPlayer) be themed. Also, I have noticed that through the dev update a few days ago, the photos app was no longer themed on my iPad. I dug around in iFile but couldn't find the culprit, so I just replaced the photo folder with the one from the non-dev version of minimal.ios.8. Don't know if this issue is for everybody, or just me.

**Comment by ghost** [comment]
Me too, but also for camera mail and safari
