### ISSUE TITLE
Icon request: Pebble Time

### ISSUE THREAD

**Issue by inket** [colbyfayock/minimal.iOS.8#12]
Hey again,

Pebble released a new app (for the new watch) called `Pebble Time`. We can use the old `Pebble` app's icon, but it just needs renaming?

Also, no need to worry about duplicating it because the 2 apps don't work together and the user can only use one of them!

Thank you for keeping this theme awesome! :D

**Comment by colbyfayock** [comment]
@inket themed this on latest dev release at http://cydia.fay.io - went ahead and used the new icon and just flattened it out so they were still both distinct :)

**Comment by colbyfayock** [comment]
let me know if it's not theming for some reason

**Comment by inket** [comment]
Thank you so much! It's perfect!

**Comment by colbyfayock** [comment]
:D
