### ISSUE TITLE
Icon request 

### ISSUE THREAD

**Issue by TheLonewolf69** [colbyfayock/minimal.iOS.8#13]
Can you make icon for ~~pandora~~, moviebox, gba4ios, ~~Twitter~~  , ~~appcake~~, ~~flex~~ and ~~google maps~~ thanks 

edit: adding Playbox to this issue thread

**Comment by colbyfayock** [comment]
hey @TheLonewolf69 - pandora, twitter, google maps should be themed, though simply, just flattened out. can you show me a screenshot and what device? also, won't do appcake and flex is a paid app

**Comment by n0mar** [comment]
@colbyfayock here are the details for Flex…

**Bundle ID**: com.johncoates.Flex
**App Icons** (bold are all items included under `CFBundleIconFiles` and `CFBundleIcons~ipad`):
- icon-29.png
- icon-40.png
- icon-50.png
- icon-57.png
- icon-58.png
- icon-60.png
- icon-72.png
- **icon-76.png**
- icon-80.png
- icon-100.png
- **icon-114.png**
- **icon-120.png**
- **icon-144.png**
- **icon-152.png**
- **Icon.png** (60x60)
- Icon@2x.png (120x120)

Also, can confirm Twitter, Google Maps and Pandora **are** themed. They're just not as distinct as the others…

**Comment by colbyfayock** [comment]
thanks @n0mar

**Comment by colbyfayock** [comment]
@TheLonewolf69 @n0mar Flex is up on http://cydia.fay.io - can one of you confirm it's theming?

**Comment by colbyfayock** [comment]
@TheLonewolf69 moviebox, gba4ios, and playbox i'm not seeing in Cydia, i'll theme them if you get me the info for them like n0mar did for Flex

**Comment by n0mar** [comment]
Flex is working, thank you, @colbyfayock
