### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/minimal.iOS.8#15]
Bing, FoxNow, tiny scan, Glide, yahoo sports

**Comment by colbyfayock** [comment]
yahoo sports

**Comment by colbyfayock** [comment]
winterboard icon

**Comment by BakedBroccoli** [comment]
Thanks for my new favorite theme!

Just wanted to drop a request for Swipes and Dictionary.com Premium!

**Comment by colbyfayock** [comment]
@BakedBroccoli Dictionary.com is a paid app, can you please provide the bundle ID and icon file names?

**Comment by BakedBroccoli** [comment]
@colbyfayock

Ah, of course. The bundle ID is com.reference.dictionaryadlite and the icon files are "AppIconPaid60x60"

**Comment by colbyfayock** [comment]
Swipes, Bing, FoxNow, Glide, yahoo sports themed

**Comment by BakedBroccoli** [comment]
Yayy! Do you plan on making an dictionary.com icon?

**Comment by colbyfayock** [comment]
I do! those are just the ones I have done so far.

**Comment by BakedBroccoli** [comment]
Awesome, don't mean to sound pushy. Thanks again!

**Comment by colbyfayock** [comment]
@BakedBroccoli dictionary.com is now themed :D let me know if it doesn't work!

edit: see 2.0.4, just released to http://cydia.fay.io

**Comment by BakedBroccoli** [comment]
Looks fantastic, you're the man!

**Comment by colbyfayock** [comment]
:D

**Comment by BakedBroccoli** [comment]
Hey man if you have any free time do you think you could churn out an icon for the UE BOOM app? I'm envisioning a faded pink background with a glyph of the speakers, either dual or single like in the app here: http://i.imgur.com/HffbLHX.png

The bundle ID is com.logitech.ue.ueboom and the icon files are AppIcon57x57 and AppIcon60x60

Free app. Thanks!

**Comment by colbyfayock** [comment]
Sure, I'm moving it to a new ticket :) i'll tag you on it
