### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by ghost** [colbyfayock/minimal.iOS.8#18]
- AnyList 
- AOLReader 
- Buffer 
- Camera++
- Check the Weather 
- Cocoa Top (Cydia)
- Crash Reporter (Cydia)
- Dark Sky
- Delivered!
- Duo Mobile
- Emoji++ 
- Enpass
- First State 
- GV Mobile + 
- Instapaper 
- iTip 
- Mail to Self 
- Mango Money 
- NAVIGON 
- Pastebin 
- PkgBackup (Cydia)
- Ringtone Designer Pro
- Slate 
- Timehop 
- Truecaller
- Tydlig 
- WhatFont
- Wikiwand

**Comment by n0mar** [comment]
@rhpt can you try and add the Bundle ID's and icon names to at least some of these, please? :smile:

**Comment by ghost** [comment]
I'll add more later.

```
Buffer
id: com.buffer.buffer
IconFiles: AppIcon29x29, AppIcon40x40, AppIcon57x57, AppIcon60x60

Check the Weather
id: com.crossforward.checktheweather
IconFiles: AppIcon29x29, AppIcon40x40, AppIcon60x60

Delivered!
id: com.madeatsampa.Delivered
IconFiles: AppIcon29x29, AppIcon40x40, AppIcon60x60

First State
id: com.first-state.FSB
IconFiles: AppIcon60x60

Navigon
id: com.navigon.NavigonMyRegionUSEast
IconFiles: Icon60, Icon

Pastebin
id: uk.co.euphoricpanda.pastebin
IconFile: icon.png
IconFiles: icon.png, icon@2x.png, icon_ipad.png, icon_ipad@2x.png

Ringtone Designer Pro
id: com.blackoutlabs.rfactpro
IconFile: icon-57.png
IconFiles: Icon-57.png, Icon-114.png
```

**Comment by colbyfayock** [comment]
thanks @rhpt this helps a lot!

**Comment by ghost** [comment]
Here's more

```
GV Mobile+ 3
com.skdevsolutions.gvmobile
AppIcon29x29, AppIcon40x40, AppIcon57x57, AppIcon60x60

Emoji++
com.crossforward.EmojiKeyboard
AppIcon40x40, AppIcon60x60

First State
com.first-state.FSB
AppIcon60x60

Soundhound (Paid)
com.melodis.midomi.
AppIcon-Inf29x29, AppIcon-Info40x40, AppIcon-Inf60x60

Wikiwand
com.wikiwand.wikiwand
AppIcon29x29x, AppIcon40x40, AppIcon60x60

CrashReporter (Cydia)
Cocoa Top (Cydia)
```

**Comment by colbyfayock** [comment]
@rhpt soundhound paid should already be done, can you throw me a screenshot to verify?

also for the two cydia apps CrashReporter and Cocoa Top can you screenshot what they currently look like naturally?

**Comment by ghost** [comment]
Crash Reporter
![CrashReporter](http://cs3-3.4pda.to/2795674.png)

CocoaTop
![CocoaTop](http://cydia.saurik.com/icon@2x/ru.domo.cocoatop.png)

**Comment by colbyfayock** [comment]
@rhpt thanks :+1:

**Comment by colbyfayock** [comment]
Buffer, Check the Weather, Delivered, Emoji++, First State Bank, GV Mobile+ 3, Navigon, Pastebin, and Ringtone Designer Pro are available on my dev repo http://cydia.fay.io :) would appreciate you letting me know if they work!
https://github.com/colbyfayock/minimal.iOS.8/releases/tag/2.1.1

**Comment by n0mar** [comment]
- Apple Watch icon looks good. 
- VSCO seems to not be themed (released notes say it should be)
- Music for iOS 8.4 still needs to be themed / renamed with `App Icon29x29@2x`, `App Icon40x40@2x`, `App Icon60x60@2x`, with the Bundle ID of `com.apple.Music`

**Comment by ghost** [comment]
Looks good! Thank you!

**Comment by colbyfayock** [comment]
@tjahjono can you get the bundle id and file names for CrashReporter and CocoaTop? The icons are ready, just need that

You should be able to see Wikiwand with the latest update 2.1.2 on my dev repo http://cydia.fay.io - can you confirm that's working?

**Comment by ghost** [comment]
CocoaTop is ru.domo.CocoaTop
CrashReporter is crash-reporter

Wikiwand looks good!

**Comment by colbyfayock** [comment]
@tjahjono thanks!!! any chance you can get the filenames too? :D

**Comment by ghost** [comment]
Crash Reporter
![Crash Reporter](https://cloud.githubusercontent.com/assets/756116/9644871/1cafeffa-518e-11e5-9a6a-7e6319a100cb.png)

CocoaTop is just Icon.png

**Comment by colbyfayock** [comment]
pretty sure these are done in the previous release. if not, they'll be in next release
