### ISSUE TITLE
Icons not theming correctly on 6+

### ISSUE THREAD

**Issue by ghost** [colbyfayock/minimal.iOS.8#19]
Activator, AppInfo, and Google+ does not seem to be theming on a 6+

Edit: adding Apple Maps (6+ on 8.3)

**Comment by n0mar** [comment]
@rhpt could you give the App Icon names for any? An update will be out much faster if you can provide @colbyfayock with everything! :smile:

**Comment by ghost** [comment]
**Google+**
- icon-29.png
- icon-29@2x.png
- icon-40.png
- icon-40@2x
- icon-50
- icon-50@2x
- icon-57
- icon-57@2x
- icon-60@2x
- icon-72
- icon-72@2x
- icon-76
- icon-76@2x

I can't find the list of icons for Activator and AppInfo. I have been told, however, that you can't theme Activator without modyfing a plist.

**Comment by colbyfayock** [comment]
@rhpt hm i have all of those themed for G+, if you wanna check in my config in lib/mios_icons.jsx and make sure i'm not missing something? i have the right bundle id as well... hm

i'm going to try just throwing a @3x for AppInfo. I'm releasing a dev version tonight on http://cydia.fay.io please let me know if Apple Maps and AppInfo get themed :D

**Comment by ghost** [comment]
I upgraded to the dev version. Here's what I have for AppInfo and Google+. Maps got themed.

![img_1162](https://cloud.githubusercontent.com/assets/756116/8422931/997a37c6-1ea7-11e5-8730-5f202f3b989d.PNG)

![img_1163](https://cloud.githubusercontent.com/assets/756116/8422932/997d010e-1ea7-11e5-810f-68d1bac9ce7e.PNG)

**Comment by colbyfayock** [comment]
@rhpt Google+ is correctly themed. AppInfo - any chance you can find the filenames I'm missing? i have Icon, @2x, and @3x

**Comment by n0mar** [comment]
@colbyfayock 

**Bundle ID**: `com.mileskabal.appinfo`

**CFBundleIconFiles**:
- `Icon.png` (57px)
- `Icon@2x.png` (114px)
- `IconHD.png` (512px)

**Comment by ghost** [comment]
Can you say what's been updated in the last two updates? Thanks

**Comment by colbyfayock** [comment]
Here's the change log https://github.com/colbyfayock/minimal.iOS.8/releases

**Comment by colbyfayock** [comment]
i'm including an update adding iconhd for appinfo. if that doesn't work not sure what else to tell ya, everything else is themed. the dev release is coming shortly
