### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by maaya1989** [colbyfayock/minimal.iOS.8#20]
- calcbot
- calendars 5
- voyages-sncf
- infuse
- Teevee
- itv shows 3
- itranslate
- dictionary.com
- VSCOcam
- enlight
- snapseed
- camera+
- hipstamatic
- runtastic
- runtastic six pack

**Comment by colbyfayock** [comment]
@maaya1989 can you please provide Bundle ID's and filenames for the apps listed?

dictionary.com and snapseed should already be themed. if not please post a screenshot so I can mark it as a bug. thanks

**Comment by colbyfayock** [comment]
closing until bundle id / filenames provided
