### ISSUE TITLE
icon requests

### ISSUE THREAD

**Issue by RichForever** [colbyfayock/minimal.iOS.8#21]
~~AdobeAcrobat~~
~~Allegro~~
Listonic
~~IKO~~
~~GG~~
~~Wykop~~
~~Opera Mini~~
~~Fifa 15 Companion~~
~~DatPiff~~

**Comment by colbyfayock** [comment]
Adobe Acrobat themed on http://cydia.fay.io

**Comment by RichForever** [comment]
Thank you! Patiently waiting for next update :)

**Comment by colbyfayock** [comment]
@M92PL can you please try and provide some bundle ID's and file names for the apps you listed?

**Comment by RichForever** [comment]
@colbyfayock sure, just tell me how to do that

**Comment by colbyfayock** [comment]
this should get you started: http://imgur.com/a/CQ0bN

**Comment by RichForever** [comment]
@colbyfayock hope this is it

## Allegro

com.allegro.iphone
AppIcon29x29.png
AppIcon29x29@2x.png
AppIcon29x29@2x~ipad.png
AppIcon29x29@3x.png
AppIcon29x29~ipad.png
AppIcon40x40@2x.png
AppIcon40x40@2x~ipad.png
AppIcon40x40@3x.png
AppIcon40x40~ipad.png
AppIcon50x50@2x~ipad.png
AppIcon50x50~ipad.png
AppIcon57x57.png
AppIcon57x57@2x.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png
AppIcon72x72@2x~ipad.png
AppIcon72x72~ipad.png
AppIcon76x76@2x~ipad.png
AppIcon76x76~ipad.png

## Listonic

com.listonic

## IKO

pl.pkobp.iko
AppIcon57x57.png
AppIcon57x57@2x.png
AppIcon60x60@2x.png

## GG

pl.ggnetwork.mobilne
AppIcon29x29@2x.png
AppIcon29x29@2x~ipad.png
AppIcon29x29@3x.png
AppIcon29x29~ipad.png
AppIcon40x40@2x.png
AppIcon40x40@2x~ipad.png
AppIcon40x40@3x.png
AppIcon40x40@3x~ipad.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png
AppIcon76x76@2x~ipad.png
AppIcon76x76~ipad.png

## Wykop

pl.wykop.Wykop
AppIcon57x57.png
AppIcon57x57@2x.png
AppIcon60x60@2x.png
AppIcon72x72@2x~ipad.png
AppIcon72x72~ipad.png
AppIcon76x76@2x~ipad.png
AppIcon76x76~ipad.png

## Opera Mini

com.opera.OperaMini
AppIcon29x29@2x.png
AppIcon29x29@2x~ipad.png
AppIcon29x29-ipad.png
AppIcon40x40@2x.png
AppIcon40x40@2x~ipad.png
AppIcon40x40~ipad.png
AppIcon60x60@2x.png
AppIcon76x76@2x~ipad.png
AppIcon76x76~ipad.png

## Fifa 15 Companion

com.ea.fifaultimate.bv
AppIcon29x29.png
AppIcon29x29@2x.png
AppIcon29x29@3x.png
AppIcon40x40@2x.png
AppIcon40x40@3x.png
AppIcon57x57.png
AppIcon57x57@2x.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png

## DatPiff

com.datpiff.mobile
Icon-Ipad-76.png
Icon-Ipad-152.png
Icon-Iphone-120.png
Icon-Large.png
Icon-Small-50.png
Icon-Small-50@2x.png
Icon-Small.png
Icon-Small@2x.png
Icon.png
Icon@2x-Large.png
Icon@2x.png

**Comment by colbyfayock** [comment]
that looks right! :D

**Comment by RichForever** [comment]
@colbyfayock  uff :D If you need something else let me know

**Comment by colbyfayock** [comment]
@M92PL can you get the filenames for Listonic?

You should be able to see Allegro, IKO, GG, Wykop, Opera Mini, Fifa 15, and DatPiff with the latest update 2.1.2 on my dev repo http://cydia.fay.io - can you confirm they're working?

**Comment by RichForever** [comment]
Allegro, IKO, GG, Wykop, Opera Mini, Fifa 15, and DatPiff - works great, thank you

listonic names
ico_02.png <- 144x144px
ico_03.png <- 57x57px
ico_08.png <- 120x120px

**Comment by RichForever** [comment]
@colbyfayock
could you fix Fifa icon? It looks like Fifa 15 and 16 using the same icons. I think "Fifa Companion" will be the best solution.

**Comment by colbyfayock** [comment]
listonic and fifa 16 in dev release coming shortly
