### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by Israelnub** [colbyfayock/minimal.iOS.8#23]
Hey man, I would love if you could theme these icons. I would love to send a $5 donation if I could get my homescreen all set up with your theme! Appreciate it.

~~Things (com.culturedcode.ThingsTouch) (AppIcon-(x)px) x = (29,40,50,57,60,72,76))~~
Star Wars Card Trader (com.topps.force) 
~~Tweetbot (com.tapbots.Tweetbot3) (AppIcon (x) x (x) x = (29,40,60))~~
~~Overcast (fm.overcast.overcast)~~
~~Delivered (com.madeatsampa.Delivered) (AppIcon (x) x (x) x = (29,40,60))~~
~~VscoCam (co.visualsupply.cam)~~
~~Final Fantasy War of the Lions (com.square-enix.fft) (Icon.png, Icon@2x.png, Icon-72.png, Icon-72@2x.png)~~

Thanks again, really appreciate it!

**Comment by colbyfayock** [comment]
@Israelnub tweetbot should be themed, can you add a screenshot so I can see? and overcast

getting to the others soon

**Comment by Israelnub** [comment]
It's in the middle on the dock, I'm pretty sure that's not your icon right?

Israel Dominguez

**Comment by colbyfayock** [comment]
@Israelnub not seeing the screenshot, can you email it to cydia@fay.io

**Comment by colbyfayock** [comment]
Delivered, Things, and VSCO Cam are available on my dev repo http://cydia.fay.io :) would appreciate you letting me know if they work!
https://github.com/colbyfayock/minimal.iOS.8/releases/tag/2.1.1

**Comment by Israelnub** [comment]
Yeah it looks like they worked! Just hoping you could theme the Star Wars card trader app and final fantasy tactics apps I sent you, would really appreciate that! 

Israel Dominguez

**Comment by colbyfayock** [comment]
Yup, I'll definitely get them. I'll try to include them on the next one. I've just been super busy, trying to get as many as I can :)

**Comment by Israelnub** [comment]
No worries man, really appreciate it!

Israel Dominguez

**Comment by colbyfayock** [comment]
@Israelnub can you get the file names for Star Wars Card Trader? the icon's ready, just need that info

You should be able to see Final Fantasy Tactics with the latest update 2.1.2 on my dev repo http://cydia.fay.io - can you confirm it's working?

**Comment by Israelnub** [comment]
Yeah it's work. 

Appinfo is crashing on launch on my phone. Do you know how else I can look up the icon info?

Israel Dominguez

**Comment by colbyfayock** [comment]
Are you technical at all? willing to try and fix it? this might work... https://www.reddit.com/r/jailbreak/comments/2oenez/fix_appinfo_to_work_with_ios_8_also_fix_pc_apps/ no guarantees.

someone else mentioned: "I use tweak called icon tool to determine bundle id and iFile to go to info.plist for the apps to find their filename."

Can also take a look at these:
https://www.reddit.com/r/iOSthemes/comments/1uv8iz/ive_made_an_image_tutorial_on_how_to_make_a_theme/
http://imgur.com/a/CQ0bN

The tutorial above is pretty good and the comments in the reddit link might go into some good detail

**Comment by Israelnub** [comment]
I mean I usually know what I'm doing but this is way out of my depth hahaha

I'll keep trying but wouldn't it be easier for you to just download the app and look it up? It's free. 

Israel Dominguez

**Comment by Israelnub** [comment]
Also I've done that fix, it's an old fix and after looking stuff up in the subreddit appinfo has apparentl been down for a couple months. 

Israel Dominguez

**Comment by colbyfayock** [comment]
@Israelnub for one app, yeah, it'd be easier. Unfortunately I lost my jailbreak because I shattered my screen and got it replaced with the newest iOS, so I have no way of doing that :/

**Comment by colbyfayock** [comment]
coming next dev release
