### ISSUE TITLE
Icon Requests (iPad)

### ISSUE THREAD

**Issue by h4ck-y0u** [colbyfayock/minimal.iOS.8#24]
A few key icons that are missing or not working for the iPad.
- ~~Safari~~
- PhotoBooth
- ~~Clock~~
- ~~Photos~~
- ~~Skype~~
- ~~Camera~~
- ~~Clock~~
- MEGA

I have no other Winterboard entries besides minimal.iOS.8 so no conflicts should be occuring.

Regards, 
h4ck_y0u - /r/iOSthemes
iPad 3rd Gen, iOS 8.3

**Comment by colbyfayock** [comment]
Safari, Clock, Photos, Camera all fixed in 2.0.3 via http://cydia.fay.io

**Comment by h4ck-y0u** [comment]
Thanks Colby, I replied to your comment on reddit. Also, I've created my own icons for MEGA (very basic) as I noticed it was currently not on the icon list. If you're interested, they can be found at http://imgur.com/a/zyEYe

I just copied the com.apple.camera folder inside your updated dev folder and replaced each image with a different one, keeping the resolutions the same.

If you use them awesome, if not, all good. Thanks for your hard work :)

**Comment by colbyfayock** [comment]
@h4ck-y0u well the only thing i'd say is i would want the actual "M" that MEGA uses. so with that in mind, do you use photoshop? also are you familiar at all with the command line? id be happy to accept a pull request with the icon psd if you can figure out how to do that. i still need to document my new contributing workflow. should make it easy for others to help out if they'd like :D

**Comment by h4ck-y0u** [comment]
But, that is the M that Mega uses isnt it? I got it from their website. Maybe it's different per country but here in Australia, that's their logo haha. And yeah command line is fine I have Fedora next to me with git ready to go. Will sort out a few other .PSDs and make a Pull Request soon.

**Comment by colbyfayock** [comment]
Hm, weird haha not sure. But https://itunes.apple.com/us/app/mega/id706857885?mt=8 that's what I'm seeing there and on their website, mind doing that? i got lucky and found a super high res version :D you can grab it here http://d.fay.io/xJ3z

**Comment by colbyfayock** [comment]
oh, and for the psd, probably will be fine just duplicating one of the ones existing. its basically a 512x512 psd with the "framework.psd" linked as a top layer. please use those colors :)
