### ISSUE TITLE
Apple Airport Icon

### ISSUE THREAD

**Issue by rm127** [colbyfayock/minimal.iOS.8#25]
The Apple Airport Utility Icon is already masked, so If you dont apply the mask theme you will see black edges

**Comment by colbyfayock** [comment]
hey can you show me a screenshot? where can i find this? if it's the wi-fi icon, i think my icons were overridden in ios9, which i'll try to go through and fix before i release an ios9 version

**Comment by colbyfayock** [comment]
@rasiquiz moving over to minimal.iOS.9, if you're still having this issue, can you please open a new issue over there and I'll try to take care of it before I release v1 of that?

https://github.com/colbyfayock/minimal.iOS.9

Thanks, closing this one out
