### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by rm127** [colbyfayock/minimal.iOS.8#26]
Screens by Edovia
Prompt by Panic
BarMagnet from Cydia
MusixMatch
Ecoute
Squire
~~AppCake ._.~~
CrashReporter
Flex (resolution problem on 6 Plus)

**Comment by colbyfayock** [comment]
@rasiquiz can you take a screenshot and show me the natural BarMagnet and CrashReporter icon?

**Comment by colbyfayock** [comment]
@rasiquiz can you also please try to provide bundle ID and icon file names for the requested apps?

**Comment by rasiquiz** [comment]
<img width="236" alt="screen shot 2015-07-28 at 22 56 57" src="https://cloud.githubusercontent.com/assets/9870401/8943644/16992646-357c-11e5-92c5-3b7973b5713f.png">
![Uploading Screen Shot 2015-07-28 at 22.57.06.png…]()
<img width="266" alt="screen shot 2015-07-28 at 22 57 41" src="https://cloud.githubusercontent.com/assets/9870401/8943645/16c08a56-357c-11e5-8717-29714b470967.png">
<img width="179" alt="screen shot 2015-07-28 at 22 57 32" src="https://cloud.githubusercontent.com/assets/9870401/8943646/16c2dc8e-357c-11e5-94c6-83fb09358a16.png">

**Comment by rm127** [comment]
<p><b>BarMagnet</b></p>

<img width="236" alt="screen shot 2015-07-28 at 22 56 57" src="https://cloud.githubusercontent.com/assets/9870401/8943659/2733d46a-357c-11e5-8ab7-bc5954b8736a.png">
<img width="278" alt="screen shot 2015-07-28 at 22 57 06" src="https://cloud.githubusercontent.com/assets/9870401/8943658/27338ee2-357c-11e5-86a4-caf3a9d9a82e.png">

<p><b>CrashReporter</b></p>

<img width="266" alt="screen shot 2015-07-28 at 22 57 41" src="https://cloud.githubusercontent.com/assets/9870401/8943660/27358454-357c-11e5-890b-c0adbbc1f8db.png">
<img width="179" alt="screen shot 2015-07-28 at 22 57 32" src="https://cloud.githubusercontent.com/assets/9870401/8943661/2737b166-357c-11e5-9bf3-5e83bb5933f0.png">

**Comment by colbyfayock** [comment]
crash reporter is either in the latest or will be in the one coming shortly. still need some bundle id's though

**Comment by FirePanther** [comment]
coda (com.panic.DietCoda) is the only app i bought from panic for ios, but i googled the bundle id of prompt: com.panic.Prompt2

**Comment by colbyfayock** [comment]
- BarMagnet will be added shortly
- Added a 180 icon for flex, let me know if that fixes it 
- Closing out without the rest of the ids / filenames

**Comment by colbyfayock** [comment]
using com.quarter.barmagnet for barmagnet. crossing my fingers it's right :) someone who has it, let me know later if it works :D

**Comment by FirePanther** [comment]
It should be: Quarter.BarMagnet

edit: yep
<img width="319" alt="screenshot 2015-11-04 at 03 28 29" src="https://cloud.githubusercontent.com/assets/1711106/10927928/29f15324-82a4-11e5-9fa7-e2e4c6c28efa.png">

**Comment by colbyfayock** [comment]
thanks @FirePanther i'll get that fixed next update
