### ISSUE TITLE
Icon Request: JW Library 

### ISSUE THREAD

**Issue by thewolfnears** [colbyfayock/minimal.iOS.8#29]
Bundle ID:

org.jw.jwlibrary

Icon file names 

AppIcon29x29.png 

AppIcon29x29@2x.png 

AppIcon29x29@2x~ipad.png 

AppIcon29x29@3x.png 

AppIcon29x29~ipad.png 

AppIcon40x40@2x.png 

AppIcon40x40@2x~ipad.png

AppIcon40x40@3x.png 

AppIcon40x40~ipad.png 

AppIcon50x50@2x~ipad.png 

AppIcon50x50~ipad.png 

AppIcon57x57.png 

AppIcon57x57@2x.png 

AppIcon60x60@2x.png 

AppIcon60x60@3x.png 

AppIcon72x72@2x~ipad.png 

AppIcon72x72~ipad.png 

AppIcon76x76@2x~ipad.png 

AppIcon76x76~ipad.png

**Comment by colbyfayock** [comment]
this is coming in a dev release shortly v2.1.3. please let me know if it doesnt work :)

**Comment by thewolfnears** [comment]
Thank you for making an icon for this app!

You have no idea how many times I've requested this app only to be ignored.

I truly appreciate you taking the time to make an icon.

**Comment by colbyfayock** [comment]
:) my pleasure
