### ISSUE TITLE
Whatsapp and cydia

### ISSUE THREAD

**Issue by gabrieleancora** [colbyfayock/minimal.iOS.8#3]
After the lastest update to 1.7 whatsapp And cydia icon are no more themed! i think you messed up something :c

**Comment by CasualDeveloper** [comment]
Yup. I checked the theme folder and a LOT of other icons are missing compared to the dev version.

**Comment by colbyfayock** [comment]
@diavolodeejay @KaiHD i'm looking into it. reinstalling the theme with a respring worked for me. I'm not sure what happened.... can you try that and see if it works for now?

**Comment by gabrieleancora** [comment]
I already tried some hours ago..After I downloaded the deb from here, i installed it and respringed and it's all working perfectly.

—
Inviato da Mailbox

**Comment by CasualDeveloper** [comment]
Have reinstalled and resprung. Didn't help.

**Comment by CasualDeveloper** [comment]
(I reinstalled the one from ModMyi)

**Comment by colbyfayock** [comment]
a modmyi person is looking into what's wrong. hoping to hear something soon to get a fix out. not sure what happened

**Comment by colbyfayock** [comment]
@KaiHD @diavolodeejay Fix is out on Cydia! :) Let me know if you still have any issues
