### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by rckillers110** [colbyfayock/minimal.iOS.8#30]
AppStore(india):
Saavn - com.Saavn.Saavn
Paytm - com.one97.paytm
Mobikwik - com.mobikwik
Freecharge - com.freecharge.ios
BookMyShow - BookMyShow.com
Amity University - net.amizone 
Amizoner- com.legalimpurity.amizoner

Apple product:
~~AppleWatch - com.apple.Bridge~~
NewsStand -

AppStore(All):
TrueCaller - com.truesoftware.TrueCallerOther
Notification for Reddit - com.redbanhammer.NotificationForReddit
NinType - com.jormy.nintype
WhirliBird - WhirlyBird.WhirlyBird
Monument Valley - com.ustwo.monumentvalley
imgur - imgurmobile
GhostBin - com.w00tylab.ghostbin
DailyRounds - org.dailyrounds.dailyrounds

Tweaks:
Csources2 (very bad icon) - com.dirtybeans.CSources2
CrashReporter - crash-reporter
Filza - com.tigisoftware.Filza
CallRecorder - org.hacx.callrecorder
Safari Downloader+ - com.ouraigua.safaridownloaderplus
Display Recorder - com.booleanmagic.displayrecorder
BundleIds - com.sassoty.bundleids
AnyDrop3 - me.freemanrepo.AnyDrop-3
AudioRecorder - net.limneos.AudioRecorder
Bridge - de.j-gessner.bridge
Barrel - com.aaronash.BarrelSettings
AirBlue Sharing - com.if0rce.AirBlueSharing
Mimir - com.cortexdevteam.wingedgudda
PkgBackup - com.pragmatixconsulting.packagebackup
MyWi - com.intelliborn.MyWi
Intellixscreen - com.intelliborn.intelliscreenx
AnyRing - com.iphsoft.anyring
CallBar - net.limneos.callbarapplication
AudioExplorer+ - net.erike.audioexplorerplus
TagExplorer - net.erike.tagexplorer
CoverArtExplorer - net.erike.coverartexplorer
OneHandWizard - com.gx5.onehandwizard

**Comment by colbyfayock** [comment]
Thanks. Can you also grab the icon file names please?

**Comment by rckillers110** [comment]
yes i can, but it will take some time

:)

any fast way if you know?

**Comment by colbyfayock** [comment]
hmmm well... if im doing a big batch, i'll download the icon folders to my desktop and find the files that are right. other times i'll ssh in and just look up the file names to match. not the greatest process haha but it's been working

**Comment by rckillers110** [comment]
Ok, i will find them

Why don't you use icon bundles ;)
You won't require icon name anymore :P

**Comment by rckillers110** [comment]
Hey, i asked a designer , my friend :P
He said, use IconBundles , i don't beed to search , iconbundles will do itself

**Comment by colbyfayock** [comment]
Yeah, well correct me if I'm wrong, but doesn't the iconbundles not theme EVERYTHING? Like, settings icons, notification center icons, etc etc? I've thought about switching over but i feel like I can have more control with everything the way i do it

**Comment by rckillers110** [comment]
Oh, iconBundle 
Just theme the springboard icon

For others we still need to find the file and copy it

I got your point, you need small icons or just springboard icon with @2x and @3x?

**Comment by colbyfayock** [comment]
yeah, thats just why i prefer it. i like the thoroughness doing it manually provides as it grabs everything rather than having mixed icons throughout the phone. i'd be happy to do these manually, just dont expect a really quick turnaround time, i'll get to some here and there so i can do requests for other people too :)

**Comment by rckillers110** [comment]
No problem man

It will have a look at all icons, then i will edit the post and add icon names next to it :)

**Comment by colbyfayock** [comment]
sounds good :D

**Comment by rckillers110** [comment]
See this image
I guess icon bundles have the feature

**Comment by colbyfayock** [comment]
No image came through, can you try and send it again? might need to actually log in on a computer to attach it

**Comment by rckillers110** [comment]
No, i think github don't take up images sent through reply mail

No problem
Here is image : http://i.imgur.com/LCk9ryu.jpg

**Comment by colbyfayock** [comment]
Hmmmm okay. well maybe i'll give it a try and see if it could work :D thanks for pointing that out

**Comment by rckillers110** [comment]
Yes,
May be you just require bundle id :D
And your work become less

;)

Any help, i can ask my friend :)

**Comment by colbyfayock** [comment]
that would be amazingggggg. hopefully it works as i would like :D

**Comment by rckillers110** [comment]
Can we talk directly on mail
Instead of posting everything to github 😅

**Comment by colbyfayock** [comment]
sure, email cydia@fay.io

**Comment by rckillers110** [comment]
I don't know why, but my mail is failing again and again

-Rohit Bhati

**Comment by colbyfayock** [comment]
what's your email address? I'll email you

**Comment by rckillers110** [comment]
11030121053@sicsr.ac.in

-Rohit Bhati

**Comment by colbyfayock** [comment]
closing until filenames provided
