### ISSUE TITLE
Activator 1.9.4, no Icon Mask. 

### ISSUE THREAD

**Issue by h4ck-y0u** [colbyfayock/minimal.iOS.8#32]
Latest Activator seems to be ignoring the Icon Mask. 

http://i.imgur.com/rccvSgC.jpg

iPad 3rd Gen, 8.4

**Comment by colbyfayock** [comment]
@h4ck-y0u was this definitely masked before? i can't remember that it was

**Comment by colbyfayock** [comment]
closed due to inactivity. will try to address activator when i can figure out a good way to theme it
