### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by thecrimsonice** [colbyfayock/minimal.iOS.8#33]
~~Fyu.se~~
com.fyusion.Fyuse
AppIcon29x29@2x.png
AppIcon40x40@2x.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png

MyIdol
com.huanshi.camera3d
AppIcon29x29.png
AppIcon29x29@2x.png
AppIcon29x29@2x~ipad.png
AppIcon29x29@3x.png
AppIcon29x29~ipad.png
AppIcon40x40@2x.png
AppIcon40x40@2x~ipad.png
AppIcon40x40@3x.png
AppIcon40x40~ipad.png
AppIcon50x50@2x~ipad.png
AppIcon50x50~ipad.png
AppIcon57x57.png
AppIcon57x57@2x.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png
AppIcon72x72@2x~ipad.png
AppIcon72x72~ipad.png
AppIcon76x76@2x~ipad.png
AppIcon76x76~ipad.png

~~SWORKIT lite~~
AHorseCalledScarlet.Sworkit
AppIcon29x29.png
AppIcon29x29@2x.png
AppIcon29x29@2x~ipad.png
AppIcon29x29@3x.png
AppIcon29x29~ipad.png
AppIcon40x40@2x.png
AppIcon40x40@2x~ipad.png
AppIcon40x40~ipad.png
AppIcon50x50@2x~ipad.png
AppIcon50x50~ipad.png
AppIcon57x57.png
AppIcon57x57@2x.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png
AppIcon72x72@2x~ipad.png
AppIcon72x72~ipad.png
AppIcon76x76@2x~ipad.png
AppIcon76x76~ipad.png

~~Kodi~~
org.xbmc.kodi-ios
AppIcon29x29.png
AppIcon29x29@2x.png
AppIcon40x40.png
AppIcon40x40@2x.png
AppIcon50x50.png
AppIcon50x50@2x.png
AppIcon57x57.png
AppIcon57x57@2x.png
AppIcon60x60.png
AppIcon60x60@2x.png
AppIcon72x72.png
AppIcon72x72@2x.png
AppIcon76x76.png
AppIcon76x76@2x.png

**Comment by colbyfayock** [comment]
Fyu.se, Kodi, and Sworkit are available on my dev repo http://cydia.fay.io :) would appreciate you letting me know if they work!
https://github.com/colbyfayock/minimal.iOS.8/releases/tag/2.1.1
