### ISSUE TITLE
Outbank Icon Request

### ISSUE THREAD

**Issue by FirePanther** [colbyfayock/minimal.iOS.8#34]
de.stoegerit.Outbank3iOS

```
AppIcon_OutBankDE29x29@2x.png
AppIcon_OutBankDE40x40@3x.png
AppIcon_OutBankDE29x29@2x~ipad.png
AppIcon_OutBankDE40x40~ipad.png
AppIcon_OutBankDE29x29@3x.png
AppIcon_OutBankDE60x60@2x.png
AppIcon_OutBankDE29x29~ipad.png
AppIcon_OutBankDE60x60@3x.png
AppIcon_OutBankDE40x40@2x.png
AppIcon_OutBankDE76x76@2x~ipad.png
AppIcon_OutBankDE40x40@2x~ipad.png
AppIcon_OutBankDE76x76~ipad.png
```

![appicon_outbankde29x29 3x](https://cloud.githubusercontent.com/assets/1711106/8584844/547f7470-25db-11e5-9bfb-b94c2449b44c.png)
(I know, it's already pretty minimal, but I prefer your style :D)

**Comment by colbyfayock** [comment]
will be in next dev release coming shortly, let me know / reopen if there are any issues
