### ISSUE TITLE
Documents 5 Icon Request

### ISSUE THREAD

**Issue by FirePanther** [colbyfayock/minimal.iOS.8#35]
com.readdle.ReaddleDocsIPad (I use an iPhone, bundleID is still iPad)

```
Documents-120.png
Documents-152.png
Documents-180.png
Documents-29.png
Documents-29@2x.png
Documents-40.png
Documents-50.png
Documents-50@2x.png
Documents-57.png
Documents-57@2x.png
Documents-72.png
Documents-72@2x.png
Documents-76.png
Documents-80.png
Documents-87.png
```

![documents-by-readdle-4 3-for-ios-app-icon-small](https://cloud.githubusercontent.com/assets/1711106/8585149/79c4d27c-25de-11e5-9710-a52c326039df.png)

also already pretty minimal but maybe needs some marginal changes like google photos

**Comment by colbyfayock** [comment]
will be in next dev release coming shortly, let me know / reopen if there are any issues
