### ISSUE TITLE
Skitch (by Evernote) Icon Request

### ISSUE THREAD

**Issue by FirePanther** [colbyfayock/minimal.iOS.8#36]
com.evernote.Skitch.iPad (I use an iPhone 6, bundleID is still iPad?!)

```
AppIcon29x29@2x.png
AppIcon29x29@2x~ipad.png
AppIcon29x29@3x.png
AppIcon29x29~ipad.png
AppIcon40x40@2x.png
AppIcon40x40@2x~ipad.png
AppIcon40x40@3x.png
AppIcon40x40~ipad.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png
AppIcon76x76@2x~ipad.png
AppIcon76x76~ipad.png
```

![202](https://cloud.githubusercontent.com/assets/1711106/8585003/e97ea270-25dc-11e5-94ac-f5b33189c42a.png)

**Comment by colbyfayock** [comment]
will be in next dev release coming shortly, let me know / reopen if there are any issues
