### ISSUE TITLE
Scannable (by Evernote) Icon Request

### ISSUE THREAD

**Issue by FirePanther** [colbyfayock/minimal.iOS.8#37]
com.evernote.Scannable

```
AppIcon29x29@2x.png
AppIcon29x29@2x~ipad.png
AppIcon29x29~ipad.png
AppIcon40x40@2x.png
AppIcon40x40@2x~ipad.png
AppIcon40x40~ipad.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png
AppIcon76x76@2x~ipad.png
AppIcon76x76~ipad.png
```

![pr_source](https://cloud.githubusercontent.com/assets/1711106/8585063/87dd5ef2-25dd-11e5-928d-142977ab87bc.jpg)

**Comment by colbyfayock** [comment]
will be in next dev release coming shortly, let me know / reopen if there are any issues
