### ISSUE TITLE
Aliexpress Icon Request

### ISSUE THREAD

**Issue by FirePanther** [colbyfayock/minimal.iOS.8#38]
com.alibaba.iAliexpress

```
AppIcon29x29@2x.png
AppIcon29x29@3x.png
AppIcon40x40@2x.png
AppIcon40x40@3x.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png
```

Old icons (still exists in the package)

```
Icon.png
Icon120.png
Icon29.png
Icon58.png
Icon80.png
Icon@2x.png
```

(current)
![images](https://cloud.githubusercontent.com/assets/1711106/8585129/4b8bb948-25de-11e5-9e4c-dc6dcec26454.jpg)

(old)
![imgres](https://cloud.githubusercontent.com/assets/1711106/8585133/51b8e106-25de-11e5-8a50-c43442a73942.jpg)

**Comment by colbyfayock** [comment]
will be in next dev release coming shortly, let me know / reopen if there are any issues
