### ISSUE TITLE
Steam Mobile, Simple - Better Banking, and Sybu for Kodi and XBMC

### ISSUE THREAD

**Issue by murrylincoln** [colbyfayock/minimal.iOS.8#4]
Steam: https://itunes.apple.com/us/app/steam-mobile/id495369748?mt=8
Simple: https://itunes.apple.com/us/app/simple-better-banking/id479317486?mt=8
Sybu: https://itunes.apple.com/us/app/sybu-for-kodi-and-xbmc/id567524653?mt=8

Great theme, and thanks for taking requests.

**Comment by colbyfayock** [comment]
@murrylincoln check out cydia repo http://cydia.fay.io for an updated dev release with these :) will be submitting the release to modmyi within the next couple of days

**Comment by murrylincoln** [comment]
Awesome, thanks for the update!
