### ISSUE TITLE
UE BOOM

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/minimal.iOS.8#42]
Hey man if you have any free time do you think you could churn out an icon for the UE BOOM app? I'm envisioning a faded pink background with a glyph of the speakers, either dual or single like in the app here: http://i.imgur.com/HffbLHX.png

The bundle ID is com.logitech.ue.ueboom and the icon files are AppIcon57x57 and AppIcon60x60

Free app. Thanks!

**Comment by colbyfayock** [comment]
@BakedBroccoli

**Comment by BakedBroccoli** [comment]
Sweet, I'll keep an eye on this. Looking forward to it!

**Comment by colbyfayock** [comment]
@BakedBroccoli getting to this now that i'm updating for ios9 and all. i usually like to try and keep the icons super similar to the original one, just flat and to the color palette i have set up, unless i dont like the icon :P i'd be happy doing something a little different for ya, but a + and - seem a little too abstract for others to instantly recognize it. would you be okay with the UE logo?

if you're not using this anymore i'll just close it :) let me know

**Comment by colbyfayock** [comment]
closed due to inactivity. reopen if you want
