### ISSUE TITLE
A few icon requests

### ISSUE THREAD

**Issue by csudderth1** [colbyfayock/minimal.iOS.8#44]
<b>Guitar Pro</b>

ID: com.arobas-music.iGP

Icons: ic_gp_29x29, ic_gp_40x40, ic_gp_50x50, ic_gp_57x57, ic_gp_58x58, ic_gp_72x72, ic_gp_76x76, ic_gp_80x80, ic_gp_100x100, ic_gp_114x114, ic_gp_120x120, ic_gp_128x128, ic_gp_144x144, ic_gp_152x152, ic_gp_1024x1024

~~<b>Fing</b>~~

ID: overlook.fing

Icons: AppIcon29x29, AppIcon29x29@2x, AppIcon29x29@2x~ipad, AppIcon40x40, AppIcon40x40@2x, AppIcon40x40@2x~ipad, AppIcon50x50, AppIcon50x50@2x, AppIcon50x50@2x~ipad...etc. Other sizes are 57x57, 60x60, 72x72, and 76x76. Just your typical AppIcon naming convention.

<b> Network Utility for iOS </b>

ID: com.r2lab.UtilityNetwork

Icons: AppIcon

<b>Microsoft OneNote</b>

ID: com.microsoft.onenote

Icons: AppIcon

EDIT: Do you think it would also be possible to get a few generic icons? Examples would include a few generic music related ones, some computer/networking ones, etc. Thank you so very much!

**Comment by colbyfayock** [comment]
Fing is available on my dev repo http://cydia.fay.io :) would appreciate you letting me know if it works!
https://github.com/colbyfayock/minimal.iOS.8/releases/tag/2.1.1

**Comment by colbyfayock** [comment]
Guitar Pro, Microsoft OneNote, Network Utility for iOS done, will be pushed out to a dev release shortly via cydia repo http://cydia.fay.io
