### ISSUE TITLE
Icon Requests

### ISSUE THREAD

**Issue by themungbean82** [colbyfayock/minimal.iOS.8#45]
3G Unrestrictor 5 - com.kstreich-dev.3gunrestrictor.configapp
AppCake - appcake2.iphonecake.com
Viggle - net.functionxinc.oda-ota
Winterboard - com.saurik.Winterboard

**Comment by colbyfayock** [comment]
hi @themungbean82  can you also get me file names? :)
also, sorry, i wont do appcake

**Comment by colbyfayock** [comment]
closing out until file names provided
