### ISSUE TITLE
Preference Icons w/o Mask Style

### ISSUE THREAD

**Issue by themungbean82** [colbyfayock/minimal.iOS.8#46]
I run the theme without the mask, but in settings the icons are all shaped as icons with the masks.  Would it be possible to create a pack with settings that are masked as normal apple icons? Thanks.

**Comment by colbyfayock** [comment]
@themungbean82 so are you looking for basically just simply all square output?

**Comment by themungbean82** [comment]
Yes. just like as the stock icons are masked.

**Comment by colbyfayock** [comment]
@themungbean82  can you do me a favor and move these over to a new issue on the new Github page for minimal.iOS.9? it would be easier for both of us to keep track of getting these in and if you do, I'll get these all in before releasing V1 of minimal.iOS.9

https://github.com/colbyfayock/minimal.iOS.9

Thanks, closing this one out
