### ISSUE TITLE
Passbook Icon in Settings on 6 Plus

### ISSUE THREAD

**Issue by itsnoteventhedeluxe** [colbyfayock/minimal.iOS.8#47]
The Passbook settings icon is not seeming to theme coreectly in iphone 6 Plus.
![img_0007](https://cloud.githubusercontent.com/assets/13594687/9019503/1008bc80-37aa-11e5-9bd3-dfac259d4507.PNG)

**Comment by colbyfayock** [comment]
hm, odd, my phones not jailbroken right now (had to get it replaced) but i'll try and look into this fix once they release a new jailbreak

**Comment by colbyfayock** [comment]
@itsnoteventhedeluxe  I believe this is fixed now over at minimal.iOS.9, can you try and take a look and if  it's still an problem open up an issue over there?

https://github.com/colbyfayock/minimal.iOS.9

Thanks, closing this one out
