### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by jonmostowy** [colbyfayock/minimal.iOS.8#48]
Hey! Great theme, these are just icons I'd love to see done so I could have a fully themed homescreen!

Evil Apples
ESPN Fantasy Football
Newsblur
Destiny Companion App
Call of Duty Official App
Kickstarter
Fastcustomer

thanks alot!
-@m_st_wy

**Comment by colbyfayock** [comment]
@jonmostowy can you please try and gather the Bundle ID and filenames for each of the apps?

**Comment by colbyfayock** [comment]
closing out until bundle id / filenames provided
