### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by tinytime** [colbyfayock/minimal.iOS.8#49]
Love the theme! Looks great. I do have a few icons that aren't themed. Here are the Bundle ID's and App Info needed (I hope). Thank you!

7-11 App
com.sei.sherman
AppIcon29x29@2x.png
AppIcon29x29@3x.png
AppIcon40x40@2x.png
AppIcon40x40@3x.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png

Chicago Blackhawks App
com.chicagoblackhawks.Blackhawks
AppIcon-CHI57x57.png
AppIcon-CHI57x57@2x.png
AppIcon-CHI60x60@2x.png
AppIcon-CHI60x60@3x.png
AppIcon-CHI72x72@2x~ipad.png
AppIcon-CHI72x72~ipad.png
AppIcon-CHI76x76@2x~ipad.png
AppIcon-CHI76x76~ipad.png

Cartoon Saga (DragonBall Saga)
com.DragonBall.2015
AppIcon29x29.png
AppIcon29x29@2x.png
AppIcon29x29@2x~ipad.png
AppIcon29x29~ipad.png
AppIcon40x40@2x.png
AppIcon40x40@2x~ipad.png
AppIcon40x40~ipad.png
AppIcon50x50@2x~ipad.png
AppIcon50x50~ipad.png
AppIcon57x57.png
AppIcon57x57@2x.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png
AppIcon72x72@2x~ipad.png
AppIcon72x72~ipad.png
AppIcon76x76@2x~ipad.png
AppIcon76x76~ipad.png

GasBuddy
com.gasbuddymobile.gasbuddy
Release29x29.png
Release29x29@2x.png
Release29x29@2x~ipad.png
Release29x29~ipad.png
Release40x40@2x.png
Release40x40@2x~ipad.png
Release40x40~ipad.png
Release50x50@2x~ipad.png
Release50x50~ipad.png
Release57x57.png
Release57x57@2x.png
Release60x60@2x.png
Release60x60@3x.png
Release72x72@2x~ipad.png
Release72x72~ipad.png
Release76x76@2x~ipad.png
Release76x76~ipad.png

SpinMe Alarm
com.aalshura.SpinMe
AppIcon29x29.png
AppIcon29x29@2x.png
AppIcon40x40@2x.png
AppIcon40x40@2x~ipad.png
AppIcon40x40~ipad.png
AppIcon50x50@2x~ipad.png
AppIcon50x50~ipad.png
AppIcon57x57.png
AppIcon57x57@2x.png
AppIcon60x60@2x.png
AppIcon72x72@2x~ipad.png
AppIcon72x72~ipad.png
AppIcon76x76@2x~ipad.png
AppIcon76x76~ipad.png

~~Wunderground (Weather Underground)~~
com.wunderground.weatherunderground
AppIcon29x29@2x.png
AppIcon29x29@2x~ipad.png
AppIcon29x29@3x.png
AppIcon29x29~ipad.png
AppIcon40x40@2x.png
AppIcon40x40@2x~ipad.png
AppIcon40x40@3x.png
AppIcon40x40~ipad.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png
AppIcon76x76@2x~ipad.png
AppIcon76x76~ipad.png

**Comment by tinytime** [comment]
Oooooo Sorry, and Wunderground (search that and it'll be first) thanks!

**Comment by tinytime** [comment]
Sorry here's the Bundle ID's and App Info (I hope):

7-11
com.sei.sherman
AppIcon29x29@2x.png
AppIcon29x29@3x.png
AppIcon40x40@2x.png
AppIcon40x40@3x.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png

Blackhawks App
com.chicagoblackhawks.Blackhawks
AppIcon-CHI57x57.png
AppIcon-CHI57x57@2x.png
AppIcon-CHI60x60@2x.png
AppIcon-CHI60x60@3x.png
AppIcon-CHI72x72@2x~ipad.png
AppIcon-CHI72x72~ipad.png
AppIcon-CHI76x76@2x~ipad.png
AppIcon-CHI76x76~ipad.png

Cartoon Saga
com.DragonBall.2015
AppIcon29x29.png
AppIcon29x29@2x.png
AppIcon29x29@2x~ipad.png
AppIcon29x29~ipad.png
AppIcon40x40@2x.png
AppIcon40x40@2x~ipad.png
AppIcon40x40~ipad.png
AppIcon50x50@2x~ipad.png
AppIcon50x50~ipad.png
AppIcon57x57.png
AppIcon57x57@2x.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png
AppIcon72x72@2x~ipad.png
AppIcon72x72~ipad.png
AppIcon76x76@2x~ipad.png
AppIcon76x76~ipad.png


GasBuddy
com.gasbuddymobile.gasbuddy
Release29x29.png
Release29x29@2x.png
Release29x29@2x~ipad.png
Release29x29~ipad.png
Release40x40@2x.png
Release40x40@2x~ipad.png
Release40x40~ipad.png
Release50x50@2x~ipad.png
Release50x50~ipad.png
Release57x57.png
Release57x57@2x.png
Release60x60@2x.png
Release60x60@3x.png
Release72x72@2x~ipad.png
Release72x72~ipad.png
Release76x76@2x~ipad.png
Release76x76~ipad.png

SpinMe
com.aalshura.SpinMe
AppIcon29x29.png
AppIcon29x29@2x.png
AppIcon40x40@2x.png
AppIcon40x40@2x~ipad.png
AppIcon40x40~ipad.png
AppIcon50x50@2x~ipad.png
AppIcon50x50~ipad.png
AppIcon57x57.png
AppIcon57x57@2x.png
AppIcon60x60@2x.png
AppIcon72x72@2x~ipad.png
AppIcon72x72~ipad.png
AppIcon76x76@2x~ipad.png
AppIcon76x76~ipad.png

Wunderground
com.wunderground.weatherunderground
AppIcon29x29@2x.png
AppIcon29x29@2x~ipad.png
AppIcon29x29@3x.png
AppIcon29x29~ipad.png
AppIcon40x40@2x.png
AppIcon40x40@2x~ipad.png
AppIcon40x40@3x.png
AppIcon40x40~ipad.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png
AppIcon76x76@2x~ipad.png
AppIcon76x76~ipad.png

**Comment by colbyfayock** [comment]
these will all be in a dev release later this evening via repo http://cydia.fay.io :) please reopen / comment if you notice any issues
