### ISSUE TITLE
Icon request: Outlook, Pebble, Midori, Redd, Clima

### ISSUE THREAD

**Issue by inket** [colbyfayock/minimal.iOS.8#5]
Hey, thank you for this theme! It's easily the best theme currently available.

I would love it if you could add the icons for these apps:
- Outlook: https://itunes.apple.com/jp/app/microsoft-outlook/id951937596?l=en&mt=8
  Currently there is already a bundle for Exchange(?) under the name `com.microsoft.exchange.iphone` that just needs renaming to `com.microsoft.Office.Outlook` (and the files inside too).
  If it looks good enough for you I can submit a pull request with the new names to make it work. But I think it looks just a bit too small compared to other icons.
- Pebble: https://itunes.apple.com/jp/app/pebble-smartwatch/id592012721?l=en&mt=8
- Midori: https://itunes.apple.com/jp/app/midori-japanese-dictionary/id385231773?l=en&mt=8
  The default icon is minimal enough right now, but it kinda clashes with other icons because of how big the letters in the icon are.
- Redd: https://itunes.apple.com/jp/app/redd-reddit-client/id777208009?l=en&mt=8
  The current Alien Blue icon is good so maybe just make a copy of it? I can submit a pull request.
- Clima: https://itunes.apple.com/jp/app/clima-weather-just-beautifully/id893902568?l=en&mt=8

Since Midori and Clima are not free apps (and Midori is so expensive), I can totally understand if it's not possible! Though I am willing to help if there is another way. (Maybe send you the app bundle?)

Thank you so much!

**Comment by colbyfayock** [comment]
@inket hm. I would love the pull request to make my life easier, but I think I'll need to make a new one anyways. that Icon was for OWA. I'll have to somehow differentiate between the two while keeping the colors consistent. OWA: https://itunes.apple.com/us/app/owa-for-iphone/id659503543?mt=8

As for the paid apps, we have 2 options that include getting them themed by me. You can either send me the bundle ID with all of the icon filenames for each of the two OR you could gift me the apps and I'll make sure they're completely themed (maybe you'd only want to do the .99 one if that)

Glad you're enjoying the theme so far :smile:

**Comment by inket** [comment]
Sweet! Thank you! If I can get your email address by DM on Twitter I'll send you the bundle and Clima.

**Comment by colbyfayock** [comment]
hiya @inket - can you check out the latest dev release (1.8.1) on repo http://cydia.fay.io and make sure Clima and Midori are working? :D All the rest seem to theme properly on my device!

https://github.com/colbyfayock/minimal.iOS.8/releases/tag/1.8.1

**Comment by inket** [comment]
Perfect!

![](http://i.imgur.com/VUoo5UP.png)

Thank you so much :D

**Comment by colbyfayock** [comment]
No problem :+1:
