### ISSUE TITLE
Icon Compression

### ISSUE THREAD

**Issue by n0mar** [colbyfayock/minimal.iOS.8#50]
Do you use compression when saving the PNG files?

On most icons you can see a bit of distortion (maybe from thin lines used in high resolution images, like 512px???) around the edges of the glyph, to the background.

Most notable around
- Facebook
- Weather
- Darkroom
- Alien Blue

I'm also running iPhone 6, iOS 8.4, running native resolution (no Upscale/LittleBrother), although, none of that should matter.

[Here is a screenshot (hopefully this image doesn't use compression)](http://i.imgur.com/xZTMWo5.jpg)

**Comment by colbyfayock** [comment]
I do use image compression via https://tinypng.com/

I'll look into it. It might also be how my tool is running through the files to resize. I'll see what I can find out

**Comment by colbyfayock** [comment]
Closing this out, thread is over at minimal.iOS.9 https://github.com/colbyfayock/minimal.iOS.9/issues/1
