### ISSUE TITLE
Icon Requests + Icon issues

### ISSUE THREAD

**Issue by mathildeo** [colbyfayock/minimal.iOS.8#51]
Kik as added 180x180 icon. Icon not working.
Facetune now has icons as "AppIcon29x29@2x.png" a.s.o

Icon Requests:
FINN.no
VG Pent.no
Infinit
Emojiary

itslearning
Elevkalender
Mattilbud

Bikbok
Only
H&M
Vero Moda
Cubes Stores
Mallzee
Sobazaar
KappAhl life & style

Thanks :)

**Comment by colbyfayock** [comment]
@mathildeo hey, any chance you can get some of the bundle ID and file names? :D

**Comment by mathildeo** [comment]
Sure!
Here you go :)

Kik


Facetune

**Comment by mathildeo** [comment]
Sure!
Is it the icon file names in the info.plist you need, or the icon file names from the folder?
Since its sometimes more icons in the folder than named in the .plist :)

**Comment by colbyfayock** [comment]
@mathildeo sorry for the delay (super busy at work and with client work) 

i'd probably say the ones in the folder BECAUSE if i cover all of the images in the folder, i'll definitely cover things like settings icons and any other lazy developers forget to include in the info.plist :)

**Comment by colbyfayock** [comment]
@mathildeo closing this out since I haven't heard from you. feel free to reopen if you can get the bundle id's and filenames. finally have a jailbroken phone again :D

**Comment by colbyfayock** [comment]
p.s. adding the facetune icon mentioned at the top and trying to add 3x images for kik. release on dev coming shortly
