### ISSUE TITLE
Icon request

### ISSUE THREAD

**Issue by slnash24** [colbyfayock/minimal.iOS.8#52]
Tactile Wars
BundleID : com.ankama.tactilwar

**Comment by colbyfayock** [comment]
@slnash24 any chance you can also get the filenames?

**Comment by slnash24** [comment]
How would I go about doing so?

**Comment by colbyfayock** [comment]
I'm gonna write up a tutorial this weekend, but so i know where to start for you, do you have ifile? if not, mac/pc?

**Comment by slnash24** [comment]
Yes I have ifile

**Comment by colbyfayock** [comment]
@slnash24 did the info from the other thread help at all or do you need more info still? i obviously haven't had a chance to put togehter a guide :( plus im jailbreakless right now because i had to get a new phone (drop, shatter, cry)
