### ISSUE TITLE
Icon Reqest

### ISSUE THREAD

**Issue by firerock2013** [colbyfayock/minimal.iOS.8#53]
I would like to request some icon. Hopefully you can consider my request. Here is the list : 
1. Cydia Impactor 
   Bundle Id : com.saurik.Impactor
2. Forza Football - Soccer Live Scores
   Bundle Id : com.footballaddicts.livescoreaddicts
   AppIcon29x29
   AppIcon40x40
   AppIcon57x57
   AppIcon60x60
3. Score! Hero
   Bundle Id : com.firsttouch.story
   29x29.png
   40x40.png
   50x50.png
   57x57.png
   58x58.png
   72x72.png
   76x76.png
   80x80.png
   100x100.png
   114x114.png
   120x120.png
   144x144.png
   152x152.png
   180x180.png
4. Mextures
   Bundle Id : com.merekdavis.Mextures
   AppIcon29x29
   AppIcon40x40
   AppIcon57x57
   AppIcon60x60
5. Over 
   Bundle Id : com.gopotluck.over
   AppIcon29x29
   AppIcon40x40
   AppIcon60x60
6. Replay video editor
   Bundle Id : com.stupeflix.studio
   AppIcon29x29
   AppIcon40x40
   AppIcon60x60
   AppIcon76x76
7. Cheatsheet
   Bundle Id : com.overdesign.Cheatsheet
   AppIcon29x29
   AppIcon40x40
   AppIcon60x60
   AppIcon76x76

Hope to hear from you soon. Have a nice day.

**Comment by slnash24** [comment]
How did you get the file names?

**Comment by colbyfayock** [comment]
@slnash24 sorry i got really busy with work last week. try starting here. http://imgur.com/a/CQ0bN skip around until it tells you where to find the file names

**Comment by firerock2013** [comment]
@colbyfayock thanks for the tutorial I will try that out @slnash24 I use tweak called icon tool to determine bundle id and iFile to go to info.plist for the apps to find their filename.

**Comment by colbyfayock** [comment]
@firerock2013 no rush, as i might not get to these right away, but can you get the file names for Cydia Impactor as well? thanks

also is this what the icon looks like? http://i2.wp.com/www.ihelplounge.com/wp-content/uploads/2015/07/cydia-impactor-icon.jpg?resize=320%2C218

**Comment by firerock2013** [comment]
@colbyfayock Thanks for taking the time to look into my request. For Cydia Impactor,  I actually not too sure about filenames because it looks confusing to me but I'll send to your mail Impactor's info.plist hopefully it will help out.
my mail m.asyraf84@gmail.com

Have a great day.

**Comment by colbyfayock** [comment]
## Cydia Impactor

com.saurik.Impactor
Icon-60.png
Icon-76.png
Icon-Small-40.png
Icon-Small.png
Icon-Small@2x.png
Icon-Small-50.png
Icon-Small-50@2x.png

Here's the info from the .plist. thanks @firerock2013

**Comment by firerock2013** [comment]
@colbyfayock cool!

**Comment by colbyfayock** [comment]
these are all done :) https://github.com/colbyfayock/minimal.iOS.8/releases/tag/2.1.5
find them on dev release via repo http://cydia.fay.io

**Comment by firerock2013** [comment]
Thank you so much. I really appreciate it. My home screen is now perfect.
Looking forward for minimal.ios.9 release.

Best regard.

On Wed, Nov 4, 2015 at 12:27 PM, Colby Fayock notifications@github.com
wrote:

> Closed #53 https://github.com/colbyfayock/minimal.iOS.8/issues/53.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/colbyfayock/minimal.iOS.8/issues/53#event-454012704.

## 

Sent from my iPhone
