### ISSUE TITLE
6+ Notifications Not Masking

### ISSUE THREAD

**Issue by eddiec3** [colbyfayock/minimal.iOS.8#54]
The notification icons on my 6+ aren't being masked like the ones on the springboard are. Is there any way this could be fixed?
https://i.imgur.com/FxRozMm.jpg

**Comment by colbyfayock** [comment]
@eddiec3 if you're still having this issue, can you please move this over to the new Github for minimal.iOS.9? If so, I'll try to take care of it before v1

https://github.com/colbyfayock/minimal.iOS.9

Thanks, closing this one out
