### ISSUE TITLE
Some updated icons

### ISSUE THREAD

**Issue by FirePanther** [colbyfayock/minimal.iOS.8#55]
Hey, first of all: thank you for adding my requested icons, love them all!!

Just wanted to report, that there are some icon name changes (the devs renamed the icons).
Dropbox:

```
AppIcon29x29.png
AppIcon29x29@2x.png
AppIcon29x29@2x~ipad.png
AppIcon29x29@3x.png
AppIcon29x29~ipad.png
AppIcon40x40@2x.png
AppIcon40x40@2x~ipad.png
AppIcon40x40@3x.png
AppIcon40x40~ipad.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png
AppIcon76x76@2x~ipad.png
AppIcon76x76~ipad.png
```

YouTube:

```
Icon120x120.png
Icon152x152.png
Icon180x180.png
Icon29x29.png
Icon40x40.png
Icon58x58.png
Icon72x72.png
Icon80x80.png
Icon87x87.png
```

Whatsapp:

```
AppIcon29x29.png
AppIcon29x29@2x.png
AppIcon29x29@3x.png
AppIcon40x40@2x.png
AppIcon40x40@3x.png
AppIcon57x57.png
AppIcon57x57@2x.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png
```

Also maybe some icon redesigns needed:
I removed the icons for Google+, GoogleMobile and Google Translate, b/c of the new uppercase "G" Google-Logo.
And the Apple Wallet icon is not up to date anymore but not so important.

**Comment by colbyfayock** [comment]
fixed this on master. will push out to dev release tonight.

all except an Apple Wallet update. idk thoughts? i kinda like the one i have better than the update, its ugly imo and isn't super drastically different.

closing out for work completion

**Comment by FirePanther** [comment]
Yes, i prefer yours, too, but I am from germany, we don't use the wallet app :D 
Btw, I updated the bundle id of iCloud Drive for myself
<img width="200" alt="2015-11-03 03 37 09" src="https://cloud.githubusercontent.com/assets/1711106/10900135/69fbe74a-81dc-11e5-9bcb-bbae32c5edcd.png">
I know the bundle id is com.apple.iCloudDriveApp but in iOS 9 they just download the necessary icons:
<img width="194" alt="screenshot 2015-11-03 at 03 40 24" src="https://cloud.githubusercontent.com/assets/1711106/10900155/c03aa524-81dc-11e5-9ace-e6c9ad156e80.png">
but should be the same like dropbox (first post)

(I also could fix the calendar, it didn't work in winterboard for me but in anemone
graphic idea from here: https://dribbble.com/shots/1126021-Minimal-iOS-Theme :P )

```
    <key>CalendarIconDateSettings</key>
    <dict>
        <key>FontSize</key>
        <integer>36</integer>
        <key>FontName</key>
        <string>Helvetica-Bold</string>
        <key>TextColor</key>
        <string>rgba(49, 49, 51, 1)</string>
        <key>TextYoffset</key>
        <real>5.5</real>
    </dict>
    <key>CalendarIconDaySettings</key>
    <dict>
        <key>FontSize</key>
        <integer>8</integer>
        <key>FontName</key>
        <string>Helvetica-Bold</string>
        <key>TextColor</key>
        <string>rgba(255, 255, 255, 1)</string>
        <key>TextYoffset</key>
        <real>0.0</real>
    </dict>
```

**Comment by colbyfayock** [comment]
Hm, which one is iCloud Drive? Not sure I'm seeing or able to find the app for that one for me to add it in there. Help? :)

The calendar icon actually doesn't have the red bar at the top anymore, but glad you got it working good :D

**Comment by FirePanther** [comment]
I like the old red bar :P and the thicker font looks more flat
you have to show/turn on the icloud drive icon first:
settings > icloud > icloud drive > show on home screen

**Comment by colbyfayock** [comment]
haha yeahh. well thanks for the icloud tip. i'll have that in when i push the dev update shortly :)

**Comment by FirePanther** [comment]
:+1:
