### ISSUE TITLE
Icon Request

### ISSUE THREAD

**Issue by jtjr908** [colbyfayock/minimal.iOS.8#56]
I would like to request a few new icons. Thanks in advance!

Dashlane
com.dashlane.dahlanephonefinal
AppIcon40x40@2x.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png

Echofon
net.naan.TwitterFonPro
AppIcon29x29@2x.png
AppIcon29x29@3x.png
AppIcon40x40@2x.png
AppIcon40x40@3x.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png

ESPN Fantasy Football
com.espn.fantasyFootball
AppIcon29x29@2x.png
AppIcon29x29@3x.png
AppIcon40x40@2x.png
AppIcon40x40@3x.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png

Frontpoint
com.frontpointsecurity.FrontPoint
Icon@2x.png
Icon-72.png
Icon-76.png
Icon-120.png
Icon-144.png
Icon-152.png
Icon-180.png

Gas Buddy
com.gasbuddymoble.gasbuddy
Release29x29.png
Release29x29@2x.png
Release40x40@2x.png
Release57x57.png
Release57x57@2x.png
Release60x60@2x.png
Release60x60@3x.png

Nest
com.nestlabs.jasper.nest
icon_29.png
icon_29@2x.png
icon_29@3x.png
icon_40.png
icon_40@2x.png
icon_50.png
icon_50@2x.png
icon_57.png
icon_57@2x.png
icon_60@2x.png
icon_60@3x.png
icon_76.png
icon_76@2x.png

Woodforest Mobile Banking
com.yourcompany.Woodforest
29x29.png
40x40.png
50.png
57.png
58x58.png
60.png
72.png
76x76.png
80x80.png
100.png
114.png
12.png
144.png
152x152.png

XFinity TV
com.comcast.cim.x2
AppIcon29x29@2x.png
AppIcon40x40@2x.png
AppIcon60x60@2x.png

SmartNews
jp.gocro.SmartNews
AppIcon29x29@2x.png
AppIcon29x29@3x.png
AppIcon40x40@2x.png
AppIcon40x40@3x.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png

WorldStar
com.wshh.com
AppIcon29x29@2x.png
AppIcon40x40@2x.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png

Mint Bills
com.pageonce.ionce
AppIcon29x29@2x.png
AppIcon29x29@3x.png
AppIcon40x40@2x.png
AppIcon40x40@3x.png
AppIcon60x60@2x.png
AppIcon60x60@3x.png

Microsoft Lync 2010
com.microsoft.lync2010.iphone 
Icon.png
Icon@2x.png

**Comment by colbyfayock** [comment]
GasBuddy is already done as of yesterday, all the others are here: https://github.com/colbyfayock/minimal.iOS.8/releases/tag/2.1.6

Available on repo http://cydia.fay.io shortly

**Comment by jtjr908** [comment]
Thank you!!
