### ISSUE TITLE
Icon requests 

### ISSUE THREAD

**Issue by csudderth1** [colbyfayock/minimal.iOS.8#57]
Thanks so much for fulfilling my earlier requests. I have a few more if you wouldn't mind considering them 

Provenance
com.jamsoftonline.Provenance
AppIcon29x29@2x
AppIcon29x29@2x~ipad
AppIcon29x29@3x
AppIcon29x29~ipad
AppIcon40x40@2x
AppIcon40x40@2x~ipad 
AppIcon40x40@3x
AppIcon40x40~ipad 
AppIcon60x60@2x
AppIcon60x60@3x
AppIcon76x76@2x~ipad 
AppIcon76x76~ipad 

Appster 
com.jake0oo0.appster
Icon@2x

ServerAuditor
com.crystalnix.ServerAuditor
AppIcon (same as Provenance)

AirFloat
com.tren.AirFloat
Icon.png
Icon@2x.png
Icon-72
Icon-72@2x

Filza
com.tigisoftware.Filza
AppIcon57x57.png
AppIcon57x57@2x.png
AppIcon60x60@2x
AppIcon60x60@3x
AppIcon72x72@2x~ipad
AppIcon72x72~ipad 
AppIcon76x76@2x~ipad
AppIcon76x76~ipad

**Comment by colbyfayock** [comment]
@csudderth1 can you do me a favor and move these over to a new issue on the new Github page for minimal.iOS.9? it would be easier for both of us to keep track of getting these in and if you do, I'll get these all in before releasing V1 of minimal.iOS.9

https://github.com/colbyfayock/minimal.iOS.9

Thanks, closing this one out

**Comment by csudderth1** [comment]
Absolutely! You read my mind. I was going to email you lol
