### ISSUE TITLE
Icon List.

### ISSUE THREAD

**Issue by ghost** [colbyfayock/minimal.iOS.8#6]
In my iPad Mini, version 8.1.2 there are no icons in the following apps:

1) Apple Clock,
2) Aple Photo Booth,
3) Dumb Ways to Die 2,
4) Jetpack Joyride,
5) My Talking Tom,
6) Wattpad,
7) AppCake,
8) Movie Box,
9) MyWi and
10) Imgur Browsr.

I would appreciate if you add these icons in the next update. 

P.S. I would like an option for a circle mask as i think your theme fits perfectly on a circle mask.

**Comment by ghost** [comment]
Also, i would brefer the imgur browsr to olny have a green dot on a black backround so it is pretty minimal. Also for appcake, a blue star on a white background. :)

**Comment by colbyfayock** [comment]
@nellthan22 hey i'll get these in for ya. i'll add some alt icons for you too :) i'm working on putting together a larger release, so i'll group it in there. might take a 1-3 weeks though depending on how things go

**Comment by ghost** [comment]
I dont mind waiting. :D

**Comment by ghost** [comment]
Hello? Yould you kindly add N_eye to the request? He just had CCTV's connected to our house and the icon doesnt really fit the theme. Thanks anyway.

**Comment by colbyfayock** [comment]
@nellthan22 hiya, please try the latest dev release for Wattpad, Musicbox, and Imgur Browsr

cydia source: http://cydia.fay.io
https://github.com/colbyfayock/minimal.iOS.8/releases/tag/1.8.4

The other apps I'll need you to get me the bundle ID's and icon file names and AppCake I won't do

Thanks

**Comment by ghost** [comment]
um btw, music box?

**Comment by colbyfayock** [comment]
I also did a Musicbox, I see now that you wanted Movie Box. That is another app that I will need you to provide the bundle ID and file names.

**Comment by colbyfayock** [comment]
Also n_eye is on my to-do for next dev release

**Comment by ghost** [comment]
how will i provide you it?

**Comment by colbyfayock** [comment]
http://www.reddit.com/r/iOSthemes/comments/1uv8iz/ive_made_an_image_tutorial_on_how_to_make_a_theme/ which links to http://imgur.com/a/CQ0bN

**Comment by ghost** [comment]
il do this later as im kinda busy. :D
