### ISSUE TITLE
Need help confirming some paid apps :D

### ISSUE THREAD

**Issue by colbyfayock** [colbyfayock/minimal.iOS.8#7]
Would appreciate some help confirming some of these paid apps on the latest dev release (1.8.2). Add source http://cydia.fay.io to get at it in Cydia or grab the .deb/.zip from the releases section (https://github.com/colbyfayock/minimal.iOS.8/releases/tag/1.8.2)

PLEASE comment below, tweet, email, or whatever to confirm :)

Also if you notice any icons unthemed that probably should? Like most of the default iOS ones (except  clock for now :disappointed:  )
- Clima
- FaceTune
- Fantastical
- Midori
- ProTube for YouTube
- RadarScope
- Reeder
- Transcynd
- WakeUp
- Wolfram Alpha
- X Mod Games
- XKit

**Comment by colbyfayock** [comment]
@inket can you confirm Clima and Midori on 1.8.2?

**Comment by inket** [comment]
Hey :)

Midori is fine. Reeder has a blue-ish hue (which is probably intended)

Clima's custom icon is not working though! I tracked it down and it seems that it's just about renaming the bundle from `com.littlebigcode.Climaear` to `com.littlebigcode.Clima`

![](http://i.imgur.com/Q1JIAGc.jpg)

Thank you!

**Comment by colbyfayock** [comment]
thanks @inket i'll get that in a bug fix tonight :D the reeder updates intended. let me know if you notice anything else weird

**Comment by ghost** [comment]
Amazon and RadarScope are working great! Thanks for the updates!

**Comment by colbyfayock** [comment]
appreciate it @bdhudd :D

**Comment by colbyfayock** [comment]
@inket can you try these bug fixes :D
http://cydia.fay.io
https://github.com/colbyfayock/minimal.iOS.8/releases/tag/1.8.3

**Comment by inket** [comment]
@colbyfayock Perfect! :D Thank you ^_^

**Comment by ghost** [comment]
Wolframalpha working perfect!
![image](https://cloud.githubusercontent.com/assets/11992896/7443100/b00667d6-f165-11e4-9e85-e4ce6130e811.jpg)

**Comment by colbyfayock** [comment]
Thanks @nellthan22

**Comment by ghost** [comment]
Xmod games good
![image](https://cloud.githubusercontent.com/assets/11992896/7470055/49cda73e-f34c-11e4-8620-d8d07e4d5661.jpg)

**Comment by colbyfayock** [comment]
Thanks all :D
